spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/tareabases
    username: postgres
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
#    hibernate:
#      ddl-auto: create


server:
  port: 8080