spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: tareas
      port: 27017
      host: localhost
#spring:   
#  data:     
#    mongodb:       
#      database: PRACTICA_IBM
#      username: IBM_PRACTICE
#      password: IBM123456789
#      port: 27017
#      host: curso-platzy-lgctd.mongodb.net
#      ssl-enabled: true
#      socket-timeout: 1500
#      connect-timeout: 1000
#      max-wait-time: 1500
#      auto-connect-retry: true
#      socket-keep-alive: true
#api:
#  source: api/v1/
#  create:
#    value: create/information/students